-- Schema objetivo de pedidos-service (instalación vacía).
-- Brownfield: CREATE IF NOT EXISTS no altera tablas existentes.

CREATE TABLE IF NOT EXISTS pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    total NUMERIC(38, 2) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    motivo_cancelacion VARCHAR(255),
    fecha_creacion TIMESTAMP(6) NOT NULL,
    fecha_modificacion TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS pedido_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    nombre_producto VARCHAR(100) NOT NULL,
    precio_unitario NUMERIC(38, 2) NOT NULL,
    cantidad INTEGER NOT NULL,
    subtotal NUMERIC(38, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agregado_id BIGINT NOT NULL,
    tipo_evento VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    estado VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    fecha_publicacion TIMESTAMP(6)
);
