-- Schema objetivo de catalogo-service (instalación vacía).
-- Brownfield: CREATE IF NOT EXISTS no altera tablas existentes.

CREATE TABLE IF NOT EXISTS categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT
);

CREATE TABLE IF NOT EXISTS producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    precio NUMERIC(38, 2) NOT NULL,
    stock INTEGER NOT NULL,
    categoria_id BIGINT NOT NULL,
    estado VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    fecha_modificacion TIMESTAMP(6),
    CONSTRAINT uk_producto_nombre UNIQUE (nombre)
);

CREATE TABLE IF NOT EXISTS restock_event (
    event_id VARCHAR(100) NOT NULL PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    aplicado_en TIMESTAMP(6) NOT NULL
);
