-- Schema objetivo de notificaciones-service (instalación vacía).
-- Brownfield: CREATE IF NOT EXISTS no altera tablas existentes.

CREATE TABLE IF NOT EXISTS notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    tipo VARCHAR(255) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    referencia_id BIGINT NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMP(6) NOT NULL
);
