-- Schema objetivo de auth-service (instalación vacía).
-- Brownfield: CREATE IF NOT EXISTS no altera tablas existentes.

CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    fecha_modificacion TIMESTAMP(6),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);
