-- Schema objetivo de pagos-service (instalación vacía).
-- Brownfield: CREATE IF NOT EXISTS no altera tablas viejas; V2 añade columnas.

CREATE TABLE IF NOT EXISTS pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    monto NUMERIC(38, 2) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    motivo_rechazo VARCHAR(255),
    intento INTEGER NOT NULL DEFAULT 1,
    fecha_procesado TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_pago_pedido_intento UNIQUE (pedido_id, intento)
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agregado_id BIGINT NOT NULL,
    tipo_evento VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    estado VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP(6) NOT NULL,
    fecha_publicacion TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS configuracion (
    clave VARCHAR(64) NOT NULL PRIMARY KEY,
    valor VARCHAR(255) NOT NULL
);
