apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
