apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
        app.kubernetes.io/part-of: ecommerce-microservices
    spec:
      containers:
        - name: kafka
          image: bitnamilegacy/kafka:3.7.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: internal
              containerPort: 29092
            - name: external
              containerPort: 9092
            - name: controller
              containerPort: 9093
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@kafka-0.kafka.ecommerce.svc.cluster.local:9093
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - (exec 3<>/dev/tcp/127.0.0.1/29092) 2>/dev/null
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - (exec 3<>/dev/tcp/127.0.0.1/29092) 2>/dev/null
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 12
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          emptyDir: {}
