apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce
resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-ecommerce-secrets.yaml
  - postgres-init-configmap.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - kafka-service.yaml
  - kafka-statefulset.yaml
  - kafka-topics-job.yaml
  - redis-service.yaml
  - redis-deployment.yaml
  - catalogo-deployment.yaml
  - catalogo-service.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - pedidos-deployment.yaml
  - pedidos-service.yaml
  - pagos-deployment.yaml
  - pagos-service.yaml
  - notificaciones-deployment.yaml
  - notificaciones-service.yaml
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - zipkin-deployment.yaml
  - zipkin-service.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-provisioning-configmap.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - ingress.yaml
