apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ecommerce
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: ecommerce-microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
